sudo: false

language: node_js

notifications:
  email: false

node_js:
  - "6"
  - "8"

services:
  - MongoDB

env:
  - NODE_ENV=travis
  - JWT_SECRET=savjbsu7864385hbhgbewoio345135sdf0ookh

cache:
  directories:
  - node_modules

before_install:
  - npm install -g npm@latest

install:
  - npm install

script: npm run test:ci
