sudo: false

language: node_js

notifications:
  email: false

node_js:
  - "6"
  - "8"

services:
  - mongodb

env:
  - NODE_ENV=test

cache:
  directories:
  - node_modules

before_install:
  - npm install -g npm@latest

install:
  - npm install

script: npm run test:ci
